### ISSUE TITLE
TinyUSB are not visible in VSCode workspace 

### ISSUE THREAD

**Issue by M0n7y5** [raspberrypi/pico-setup-windows#35]
I am not able to see TinyUsb examples in workspace folder despite being installed in Program Files/PicoSDK.

**Comment by ndabas** [comment]
Can you provide some more details? What path do you have on your system, how are you trying to view it, can you provide a screenshot of that path not being visible?

The USB-specific examples should actually be located in `C:\Users\<username>\Documents\Pico-v1.5.1\pico-examples\usb`, and not in the SDK. The SDK has TinyUSB as a submodule, but the code there isn't meant to be part of the official examples.

**Comment by ndabas** [comment]
Closing as we have not heard back from the issue author.

**Comment by patfrench** [comment]
Hello,

I have a problem and I have some questions:
can anyone help me?

* I can compile pico-examples with Vscode on windows11
* I can compile TinyUSB webserial examples on Ubuntu

Now I'd like to include TinyUSB in Vscode because I'd like to stay on windows 11.

here are my questions:
1) I'd like to modify webserial but in pico-example I can't find the sources
in `C:\Users\----\Documents\Pico-v1.5.1\pico-examples\usb\device` I find that` dev_hid_composite` and `dev_lowlevel`
if I go to `C:\Users\----\Documents\Pico-v1.5.1\pico-examples\build\usb\device\tinyusb_device_examples\webusb_serial `I find that the result of compilation

2) When I compile the Webserial example from TinyUSB I do `make BOARD=raspberry_pi_pico LOG=2` all
How do I activate `LOG=2` if I compile with Vscode pico-example? (assuming I've managed to integrate tinyusb).

3) Do you have a simple tree structure of a minimal project so that I can better understand?

I'm sorry but I have a lot of trouble with non-integrated development chains, there are so many make and cmake that I'm lost. 

Thanks in advance

**Comment by ndabas** [comment]
@patfrench sorry I did not see your post earlier -- you posted this on a closed issue.

Anyway, if this is still relevant:
1. This is explained in the [pico-examples ReadMe](https://github.com/raspberrypi/pico-examples/tree/sdk-1.5.1?tab=readme-ov-file#tinyusb-examples).
2. You can set any variable similar to [this example](https://github.com/raspberrypi/pico-setup-windows/wiki/FAQ#how-do-i-set-the-pico_board) for `PICO_BOARD`.
3. You can go through the readmes for pico-sdk and pico-examples for help on setting up a minimal tree structure.
